// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool_WebAPI.Data;

namespace SmartSchool_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Document")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "72143DA8-799B-4962-A8AE-EF926FE299C5",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 606, DateTimeKind.Local).AddTicks(7613),
                            Document = "455.278.840-00",
                            Email = "clarkkent@yahoo.com",
                            FirstName = "Clark",
                            LastName = "Kent",
                            Phonenumber = "11933225555",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(4921)
                        },
                        new
                        {
                            Id = "0530841D-AA4A-4469-9F6D-8DD39C75BD51",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6099),
                            Document = "860.187.460-69",
                            Email = "leonskennedy@hotmail.com",
                            FirstName = "Leon",
                            LastName = "Kennedy",
                            Phonenumber = "21999880033",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6124)
                        },
                        new
                        {
                            Id = "22E5557C-A61E-476F-A996-09FAB7DFF0AD",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6137),
                            Document = "730.648.440-08",
                            Email = "brucewayne@gmail.com",
                            FirstName = "Bruce",
                            LastName = "Wayne",
                            Phonenumber = "47933442121",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6141)
                        },
                        new
                        {
                            Id = "B36F6B51-3F95-4B3E-95C0-19099A78E825",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6145),
                            Document = "704.332.760-10",
                            Email = "stark@yahoo.com",
                            FirstName = "Tony",
                            LastName = "Stark",
                            Phonenumber = "1397674944",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6148)
                        },
                        new
                        {
                            Id = "B76B460B-3F15-4D71-9B31-1C0EFA20D0DE",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6151),
                            Document = "819.391.990-42",
                            Email = "hulk@hotmail.com",
                            FirstName = "Bruce",
                            LastName = "Benner",
                            Phonenumber = "45998877664",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6154)
                        },
                        new
                        {
                            Id = "E8E0015B-1EB1-444C-AF78-C0DCDE508109",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6164),
                            Document = "268.910.380-06",
                            Email = "scooby@yahoo.com",
                            FirstName = "Scooby",
                            LastName = "Doo",
                            Phonenumber = "11945492790",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6166)
                        },
                        new
                        {
                            Id = "B1FE8B94-1773-443A-9E04-52753571F3D3",
                            CreatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6169),
                            Document = "236.780.220-30",
                            Email = "charliebrown@hotmail.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            Phonenumber = "34977553040",
                            UpdatedAt = new DateTime(2020, 6, 25, 19, 21, 42, 611, DateTimeKind.Local).AddTicks(6172)
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.StudentSubject", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentsSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = "72143DA8-799B-4962-A8AE-EF926FE299C5",
                            SubjectId = "2"
                        },
                        new
                        {
                            StudentId = "72143DA8-799B-4962-A8AE-EF926FE299C5",
                            SubjectId = "4"
                        },
                        new
                        {
                            StudentId = "72143DA8-799B-4962-A8AE-EF926FE299C5",
                            SubjectId = "5"
                        },
                        new
                        {
                            StudentId = "0530841D-AA4A-4469-9F6D-8DD39C75BD51",
                            SubjectId = "1"
                        },
                        new
                        {
                            StudentId = "0530841D-AA4A-4469-9F6D-8DD39C75BD51",
                            SubjectId = "2"
                        },
                        new
                        {
                            StudentId = "0530841D-AA4A-4469-9F6D-8DD39C75BD51",
                            SubjectId = "5"
                        },
                        new
                        {
                            StudentId = "22E5557C-A61E-476F-A996-09FAB7DFF0AD",
                            SubjectId = "1"
                        },
                        new
                        {
                            StudentId = "22E5557C-A61E-476F-A996-09FAB7DFF0AD",
                            SubjectId = "2"
                        },
                        new
                        {
                            StudentId = "22E5557C-A61E-476F-A996-09FAB7DFF0AD",
                            SubjectId = "3"
                        },
                        new
                        {
                            StudentId = "B36F6B51-3F95-4B3E-95C0-19099A78E825",
                            SubjectId = "1"
                        },
                        new
                        {
                            StudentId = "B36F6B51-3F95-4B3E-95C0-19099A78E825",
                            SubjectId = "4"
                        },
                        new
                        {
                            StudentId = "B36F6B51-3F95-4B3E-95C0-19099A78E825",
                            SubjectId = "5"
                        },
                        new
                        {
                            StudentId = "B76B460B-3F15-4D71-9B31-1C0EFA20D0DE",
                            SubjectId = "4"
                        },
                        new
                        {
                            StudentId = "B76B460B-3F15-4D71-9B31-1C0EFA20D0DE",
                            SubjectId = "5"
                        },
                        new
                        {
                            StudentId = "B76B460B-3F15-4D71-9B31-1C0EFA20D0DE",
                            SubjectId = "1"
                        },
                        new
                        {
                            StudentId = "E8E0015B-1EB1-444C-AF78-C0DCDE508109",
                            SubjectId = "2"
                        },
                        new
                        {
                            StudentId = "E8E0015B-1EB1-444C-AF78-C0DCDE508109",
                            SubjectId = "3"
                        },
                        new
                        {
                            StudentId = "E8E0015B-1EB1-444C-AF78-C0DCDE508109",
                            SubjectId = "4"
                        },
                        new
                        {
                            StudentId = "B1FE8B94-1773-443A-9E04-52753571F3D3",
                            SubjectId = "1"
                        },
                        new
                        {
                            StudentId = "B1FE8B94-1773-443A-9E04-52753571F3D3",
                            SubjectId = "3"
                        },
                        new
                        {
                            StudentId = "B1FE8B94-1773-443A-9E04-52753571F3D3",
                            SubjectId = "4"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Aritmética",
                            TeacherId = "1"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Física",
                            TeacherId = "2"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Português",
                            TeacherId = "3"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Informática",
                            TeacherId = "4"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Culinária",
                            TeacherId = "5"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            FirstName = "Girafales",
                            LastName = "Gonzales"
                        },
                        new
                        {
                            Id = "2",
                            FirstName = "Pardal",
                            LastName = "Voador"
                        },
                        new
                        {
                            Id = "3",
                            FirstName = "Raimundo",
                            LastName = "Nonato"
                        },
                        new
                        {
                            Id = "4",
                            FirstName = "Alexsandro",
                            LastName = "Andrade"
                        },
                        new
                        {
                            Id = "5",
                            FirstName = "Gladys",
                            LastName = "Moreno"
                        });
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.StudentSubject", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Student", "Student")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool_WebAPI.Models.Subject", "Subject")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool_WebAPI.Models.Subject", b =>
                {
                    b.HasOne("SmartSchool_WebAPI.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");
                });
#pragma warning restore 612, 618
        }
    }
}
